package cn.edu.nuc1.ui.manage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import cn.edu.nuc1.DBSystemManage;
import cn.edu.nuc1.utils.ModifyTable;
import cn.edu.nuc1.utils.ShowTable;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Administrator
 */
public class AdminSendDeleteUpdate extends javax.swing.JFrame {

    /**
     * Creates new form AdminSendDeleteUpdate
     * @param mO
     */
    public AdminSendDeleteUpdate(Object[] mO) {

        initComponents(mO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param mO
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(Object[] mO) {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("管理员编号：");

        jLabel2.setText("教材编号：");

        jLabel3.setText("领书人姓名：");

        jLabel4.setText("领书数量：");

        jLabel5.setText(" 领书日期：");

        jLabel6.setText("教材名字");

        jButton1.setText("修改");

        jButton2.setText("删除");
        JTextField[]mJTextFields=new JTextField[6];
        mJTextFields[0]=jTextField1;
        mJTextFields[1]=jTextField2;
        mJTextFields[2]=jTextField3;
        mJTextFields[3]=jTextField4;
        mJTextFields[4]=jTextField5;
        mJTextFields[5]=jTextField6;
        jButton1.addActionListener(e -> updataAction(e,mO));
        jButton2.addActionListener(e -> deleteAction(e));
        for (int i=0;i<mO.length;i++){
            mJTextFields[i].setText(mO[i].toString());

        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(42, 42, 42)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addContainerGap()
                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(28, 28, 28)
                                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel5)
                                                                .addGap(9, 9, 9)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTextField1)
                                                        .addComponent(jTextField2)
                                                        .addComponent(jTextField3)
                                                        .addComponent(jTextField4)
                                                        .addComponent(jTextField5)
                                                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(74, Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(56, 56, 56)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>

    private void deleteAction(ActionEvent mE) {
        String SMno = jTextField1.getText();
        String SBno = jTextField2.getText();
        String Lname = jTextField3.getText();
        String Bnum = jTextField4.getText();
        String Data = jTextField5.getText();
        String Bname = jTextField6.getText();
        ModifyTable mModifyTable = new ModifyTable(DBSystemManage.getInstance().mStatement);
        String sql = "delete from send where SMno='"+SMno+"'and "+
                                             "SBno='"+SBno+"'";

        mModifyTable.setSql(sql);
        mModifyTable.modifyRecord();
        JOptionPane.showMessageDialog(this,"删除成功");
        ShowTable.showTable(AdminManageActivity.jTable2,"select * from send",6,new String[]{"管理员编号","教材编号","领书人姓名","领书数量","领书日期","教材名字"});

        String sql3 = "select * from book where Bno ='"+SBno+"'";
        try {
            ResultSet mResultSet = DBSystemManage.getInstance().mStatement.executeQuery(sql3);
            if (mResultSet.next()){
                int all= mResultSet.getInt(5)+Integer.parseInt(Bnum);
                System.out.println(all);
                mModifyTable.setSql("update book set Bnum="+all+" where Bno ='"+SBno+"'");
                mModifyTable.modifyRecord();

            }
        } catch (SQLException mE1) {
            mE1.printStackTrace();
        }

        String sql2 ="update toget set Gdo = '否' where GBno ="+"'"+SBno+"'";
        mModifyTable.setSql(sql2);
        mModifyTable.modifyRecord();
    }

    private void updataAction(ActionEvent mE, Object[] mO) {
        String SMno = jTextField1.getText();
        String SBno = jTextField2.getText();
        String Lname = jTextField3.getText();
        String Bnum = jTextField4.getText();
        String Data = jTextField5.getText();
        String Bname = jTextField6.getText();
        String sql = "update send set SBno ="
                     +"'"+SBno+"', Lname="
                     +"'"+Lname+"', Bnum="
                     +Bnum+", Sdate ="
                     +"'"+Data+"', Bname ="
                     +"'"+Bname+"' where SBno='"+SBno+"' and SMno ='"+SMno+"'";
        ModifyTable mModifyTable = new ModifyTable(DBSystemManage.getInstance().mStatement);
        mModifyTable.setSql(sql);
        mModifyTable.modifyRecord();
        String sql3 = "select * from book where Bno ='"+SBno+"'";
        String sql4 = "select * from toget where GBno ='"+SBno+"'";
        try {
            ResultSet mResultSet = DBSystemManage.getInstance().mStatement.executeQuery(sql3);
            ResultSet mResultSet1 = DBSystemManage.getInstance().mStatement.executeQuery(sql4);
            if (mResultSet.next() && mResultSet1.next()){
                int toget =  mResultSet1.getInt(3);
                int all= mResultSet.getInt(5)+toget-Integer.parseInt(Bnum);
                System.out.println(all);
                mModifyTable.setSql("update book set Bnum="+all+" where Bno ='"+SBno+"'");
                mModifyTable.modifyRecord();

            }
        } catch (SQLException mE1) {
            mE1.printStackTrace();
        }

        ShowTable.showTable(AdminManageActivity.jTable2,"select * from send ",6,new String[]{"管理员编号","教材编号","领书人姓名","领书数量","领书日期","教材名字"});

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSendDeleteUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSendDeleteUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSendDeleteUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSendDeleteUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {new AdminSendDeleteUpdate(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration
}
