package cn.edu.nuc.utils.ui;

import cn.edu.nuc.utils.DBSystemManage;
import cn.edu.nuc.utils.utils.ModifyTable;
import cn.edu.nuc.utils.utils.ShowTable;
import com.sun.org.apache.xpath.internal.operations.Mod;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;

/**
 * Created by Administrator on 2018/1/18.
 */
public class ManagerActivity extends javax.swing.JFrame {

    private Statement mStatement = DBSystemManage.getInstance().mStatement;
    private String finalManagerId;
    /**
     * Creates new form ManagerActivity
     */

    public ManagerActivity(String user) {
        finalManagerId ="a1";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jM1BookTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jM1Area = new javax.swing.JTextArea();
        jM1SendBtn = new javax.swing.JButton();
        jM1ShowBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jM2KuncunTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jM2OrderNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jM2OrderBookNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jM2OrderNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jM2Dateld4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jM2ChubansheNo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jM2ChubansheTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jM2Btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jM3Name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jM3Tel = new javax.swing.JTextField();
        jM3Pass = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jM3SubBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setForeground(new java.awt.Color(102, 204, 255));

        jM1BookTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jM1BookTable);

        jM1Area.setColumns(20);
        jM1Area.setRows(5);
        jScrollPane3.setViewportView(jM1Area);

        jM1SendBtn.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jM1SendBtn.setText("发放");
        jM1SendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM1SendBtnActionPerformed(evt);
            }
        });

        jM1ShowBtn.setText("显示未处理的");
        jM1ShowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM1ShowBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("教材申请情况");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(62, 62, 62)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jM1SendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(211, 211, 211)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(203, 203, 203)
                                                .addComponent(jM1ShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53)
                                                .addComponent(jM1SendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addComponent(jM1ShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("教材发放", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jM2KuncunTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane2.setViewportView(jM2KuncunTable);

        jLabel2.setText("征订号");

        jLabel3.setText("征订库存号");

        jM2OrderBookNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM2OrderBookNoActionPerformed(evt);
            }
        });

        jLabel4.setText("征订数量");

        jLabel5.setText("征订日期");

        jLabel6.setText("管理员ID");

        jM2ChubansheTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane4.setViewportView(jM2ChubansheTable);

        jLabel8.setText("库存信息");

        jLabel9.setText("出版社信息");

        jM2Btn.setText("征订");
        jM2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM2BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(93, 93, 93)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(jLabel6))
                                                                .addGap(43, 43, 43)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jM2OrderNo)
                                                                        .addComponent(jM2OrderBookNo)
                                                                        .addComponent(jM2OrderNum)
                                                                        .addComponent(jM2Dateld4)
                                                                        .addComponent(jM2ChubansheNo, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(159, 159, 159)
                                                                .addComponent(jM2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(240, 240, 240)
                                                .addComponent(jLabel8))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(252, 252, 252)
                                                .addComponent(jLabel9)))
                                .addGap(174, 174, 174))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jM2OrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(39, 39, 39)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jM2OrderBookNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(44, 44, 44)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jM2OrderNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(49, 49, 49)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jM2Dateld4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(41, 41, 41)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jM2ChubansheNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(84, 84, 84)
                                                .addComponent(jM2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        jTabbedPane1.addTab("教材征订", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        jLabel7.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel7.setText("个人信息修改");

        jLabel10.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        jLabel10.setText("姓名");

        jLabel11.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        jLabel11.setText("密码");

        jM3Tel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        jLabel12.setText("手机");

        jM3SubBtn.setText("修改");
        jM3SubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM3SubBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(458, 458, 458)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel12))
                                                .addGap(76, 76, 76)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jM3Pass)
                                                        .addComponent(jM3Name)
                                                        .addComponent(jM3Tel, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(131, 131, 131)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(252, 252, 252))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jM3SubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(341, 341, 341))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jM3Name, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(jM3Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel7)
                                .addGap(49, 49, 49)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jM3Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addComponent(jM3SubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
        );

        jTabbedPane1.addTab("个人信息修改", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );
        pack();
        jM1();
        jM2();
        jM3();
        jTabbedPane1.addChangeListener(e -> {
            if (jTabbedPane1.getSelectedIndex() == 0){
                String sql = "select Ano,apply.Bno,Tno,Anum,Adate,Snum,Ado from apply,store where apply.Bno = store.Bno";
                ShowTable.showTable(jM1BookTable,sql,7,new String[]{"申请编号","申请书编号","教师编号","申请数量","申请日期","库存","被处理？"});
            }else if (jTabbedPane1.getSelectedIndex() == 1){

            }
        });

    }// </editor-fold>
    public void jM1(){
        String sql = "select Ano,apply.Bno,Tno,Anum,Adate,Snum,Ado from apply,store where apply.Bno = store.Bno";
        ShowTable.showTable(jM1BookTable,sql,7,new String[]{"申请编号","申请书编号","教师编号","申请数量","申请日期","库存","被处理？"});
        jM1ShowBtn.addActionListener(e12 -> {
            System.out.println("click");
            String sql2 = "select Ano,apply.Bno,Tno,Anum,Adate,Snum,Ado from apply,store where apply.Bno = store.Bno and Ado = 'no'";
            ShowTable.showTable(jM1BookTable,sql2,7,new String[]{"申请编号","申请书编号","教师编号","申请数量","申请日期","库存","被处理？"});
        });
        jM1BookTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int r= jM1BookTable.getSelectedRow();
                String[] mO =new String[jM1BookTable.getColumnCount()];
                for (int i=0;i<jM1BookTable.getColumnCount();i++){
                    mO[i]= jM1BookTable.getValueAt(r, i).toString().trim();
                    System.out.println(mO[i]);
                }
                jM1Area.setText("\n申请编号:  "+mO[0]+"\n"+
                                "\n申请书编号:  "+mO[1]+"\n"+
                                "\n教师编号:  "+mO[2]+"\n"+
                                "\n申请数量:  "+mO[3]+"\n"+
                                "\n申请日期:  "+mO[4]+"\n"+
                                "\n库存:   "+mO[5]+"\n"+
                                "\n是否被处理:   "+mO[6]+"\n"
                );
                final String dNo = "d"+mO[0];
                final String bNo = mO[1];
                final String dNum = mO[3];
                final String tNo = mO[2];
                final String aNo = mO[0];
                Date date = new Date();
                String year = String.format("%tY", date);
                String month = String.format("%tB", date);
                String day = String.format("%te", date);
                final String dDate = year+"/"+month+"/"+day;
                jM1SendBtn.addActionListener(e1 -> {
                    ModifyTable mModifyTable = new ModifyTable(mStatement);
                    mModifyTable.setSql("insert into deliver(Dno,Bno,Dnum,Ddate,Tno)values("
                            +"'"+dNo+"'"+","
                            +"'"+bNo+"'"+","
                            +" "+dNum+" "+","
                            +"'"+dDate+"'"+","
                            +"'"+tNo+"')");
                    mModifyTable.modifyRecord();
                    JOptionPane.showMessageDialog(ManagerActivity.this,"发放成功");
                    try {
                        ResultSet mResultSet = mStatement.executeQuery("select * from deliver where Dno="+"'"+dNo+"'");
                        if (mResultSet.next()){
                            System.out.println("成功获取信息1");
                            mModifyTable.setSql("update apply set Ado="+"'"+"yes"+"' where Ano = "+"'"+aNo+"'");
                            mModifyTable.modifyRecord();

                        }
                        ResultSet mResultSet1 = mStatement.executeQuery("select * from store where Bno="+"'"+bNo+"'");
                        if (mResultSet1.next()) {
                            System.out.println("成功获取信息2");
                            int numAll = mResultSet1.getInt("Snum");
                            int numNew = numAll - Integer.parseInt(dNum);
                            mModifyTable.setSql("update store set Snum ="  + numNew + " where Bno = " + "'" + bNo + "'");
                            mModifyTable.modifyRecord();
                            String sql = "select Ano,apply.Bno,Tno,Anum,Adate,Snum,Ado from apply,store where apply.Bno = store.Bno";
                            ShowTable.showTable(jM1BookTable,sql,7,new String[]{"申请编号","申请书编号","教师编号","申请数量","申请日期","库存","被处理？"});
                        }
                    } catch (SQLException e2) {
                        e2.printStackTrace();
                    }
                });
            }
        });
    }
    public void jM2(){
        jM2ChubansheNo.setText(finalManagerId);
        Date date = new Date();

        String year = String.format("%tY", date);
        String month = String.format("%tB", date);
        String day = String.format("%te", date);
        final String dDate = year+"/"+month+"/"+day;
        String oDate = dDate;
        jM2Dateld4.setText(oDate);
        String sql ="select Sno,Bno,Snum,store.Pno,Pname,Ptel from store,press where  store.Pno = press.Pno";
        ShowTable.showTable(jM2KuncunTable,sql,6,new String[]{"库存编号","教材编号","剩余数量","出版社","出版社名","出版社手机"});
        String sql2 = "select * from press";
        ShowTable.showTable(jM2ChubansheTable,sql2,3,new String[]{"出版社编号","出版社名字","出版社电话"});
        jM2Btn.addActionListener(e -> {
            String oNo = jM2OrderNo.getText();
            String bNo = jM2OrderBookNo.getText().trim();
            String num = jM2OrderNum.getText().trim();
            String oDate2 = jM2Dateld4.getText().trim();

            ModifyTable mModifyTable = new ModifyTable(mStatement);
            mModifyTable.setSql("insert into orderr(Ono,Mno,Onum,Odate,Sno)values("
                    +"'"+oNo+"'"+","
                    +"'"+finalManagerId+"'"+","
                    +""+num+""+","
                    +"'"+oDate2+"'"+","
                    +"'"+bNo+"')");
            mModifyTable.modifyRecord();
            System.out.println("添加成功");
            JOptionPane.showMessageDialog(ManagerActivity.this,"征订成功");
            try {
                ResultSet  mResultSet2 = mStatement.executeQuery("select * from store where Sno="+"'"+jM2OrderBookNo.getText()+"'");
                if (mResultSet2.next()){
                    System.out.println("success get");
                    int numPre = mResultSet2.getInt("Snum");
                    int numAdd = Integer.parseInt(jM2OrderNum.getText());
                    int numAll = numAdd + numPre;
                    mModifyTable.setSql("update store set Snum =" + numAll + " where Sno = " + "'" + bNo + "'");
                    mModifyTable.modifyRecord();
                    String sql3 ="select Sno,Bno,Snum,store.Pno,Pname,Ptel from store,press where  store.Pno = press.Pno";
                    ShowTable.showTable(jM2KuncunTable,sql3,6,new String[]{"库存编号","教材编号","剩余数量","出版社","出版社名","出版社手机"});
                }else {
                    System.out.println("error");
                }
            } catch (SQLException e1) {
                e1.printStackTrace();
            }


        });

    }
    public void jM3(){
        try {
            ResultSet resultSet = mStatement.executeQuery("select * FROM manager WHERE Mno = "+"'"+finalManagerId+"'");
            if (resultSet.next()){
                System.out.println("成功获取信息");
                jM3Name.setText(resultSet.getString("Mname"));
                jM3Pass.setText(resultSet.getString("Mkey"));
                jM3Tel.setText(resultSet.getString("Mtel"));

                jM3SubBtn.addActionListener(e -> {
                    ModifyTable modifyTable = new ModifyTable(mStatement);
                    modifyTable.setSql("update manager set Mname="+"'"+jM3Name.getText()+"' where Mno= "+"'"+finalManagerId+"'");
                    modifyTable.modifyRecord();
                    modifyTable.setSql("update manager set Mkey="+"'"+jM3Pass.getText()+"' where Mno = "+"'"+finalManagerId+"'");
                    modifyTable.modifyRecord();
                    modifyTable.setSql("update manager set Mtel="+"'"+jM3Tel.getText()+"' where Mno = "+"'"+finalManagerId+"'");
                    modifyTable.modifyRecord();
                    JOptionPane.showMessageDialog(ManagerActivity.this,"修改成功");


                });
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }


    }

    private void jM2BtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jM2OrderBookNoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jM1ShowBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jM1SendBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jM3SubBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerActivity("a1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jM1Area;
    private javax.swing.JTable jM1BookTable;
    private javax.swing.JButton jM1SendBtn;
    private javax.swing.JButton jM1ShowBtn;
    private javax.swing.JButton jM2Btn;
    private javax.swing.JTextField jM2ChubansheNo;
    private javax.swing.JTable jM2ChubansheTable;
    private javax.swing.JTextField jM2Dateld4;
    private javax.swing.JTable jM2KuncunTable;
    private javax.swing.JTextField jM2OrderBookNo;
    private javax.swing.JTextField jM2OrderNo;
    private javax.swing.JTextField jM2OrderNum;
    private javax.swing.JTextField jM3Name;
    private javax.swing.JTextField jM3Pass;
    private javax.swing.JButton jM3SubBtn;
    private javax.swing.JTextField jM3Tel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration
}
