package cn.edu.nuc.utils.ui;

import cn.edu.nuc.utils.DBSystemManage;
import cn.edu.nuc.utils.utils.ModifyTable;
import cn.edu.nuc.utils.utils.ShowTable;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by Administrator on 2018/1/18.
 */
public class TeacherActivity extends javax.swing.JFrame {
    private String finalTeacherId;
    private ModifyTable mModifyTable;
    private Statement mStatement = DBSystemManage.getInstance().mStatement;

    /**
     * Creates new form TeacherActivity
     */
    public TeacherActivity(String user) {

        finalTeacherId = user;
        mModifyTable = new ModifyTable(DBSystemManage.getInstance().mStatement);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT1Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jT1ClassNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jT1ClassId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jT1ClassMajor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jT1ClassNum = new javax.swing.JTextField();
        jT1Btn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jT1Kemu = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT2BookTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT2ClassTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jT2Btn = new javax.swing.JButton();
        jT2ApplyNo = new javax.swing.JTextField();
        jT2ApplyBookNo = new javax.swing.JTextField();
        jT2ApplyTeacherNo = new javax.swing.JTextField();
        jT2AppluNum = new javax.swing.JTextField();
        jT2ApplyDate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jT3Table = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jT4Btn = new javax.swing.JButton();
        jT4Name = new javax.swing.JTextField();
        jT4Tel = new javax.swing.JTextField();
        jT4Pass = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jT4Kemu = new javax.swing.JTextField();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jT1Table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jT1Table);

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        jLabel1.setText("添加自己带的班级");

        jLabel2.setText("班级编号");

        jT1ClassNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT1ClassNoActionPerformed(evt);
            }
        });

        jLabel3.setText("班级ID");

        jLabel4.setText("班级专业");

        jLabel5.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        jLabel5.setText("班级信息管理");

        jLabel6.setText("班级人数");

        jT1Btn.setText("确定录入");

        jLabel16.setText("科目");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 100, Short.MAX_VALUE)
                                                .addComponent(jT1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(85, 85, 85))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel16))
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addGap(56, 56, 56)
                                                                                                .addComponent(jT1ClassId, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addGap(56, 56, 56)
                                                                                                .addComponent(jT1ClassNo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                                .addGap(56, 56, 56)
                                                                                                .addComponent(jT1ClassMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                        .addGap(56, 56, 56)
                                                                                        .addComponent(jT1ClassNum, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                                .addGap(56, 56, 56)
                                                                                .addComponent(jT1Kemu, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(79, 79, 79)
                                                                .addComponent(jLabel1)))
                                                .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jT1ClassNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jT1ClassId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(49, 49, 49)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jT1ClassMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(38, 38, 38)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jT1ClassNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel16)
                                                        .addComponent(jT1Kemu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(63, 63, 63)
                                                .addComponent(jT1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("班级信息管理", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jT2BookTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane2.setViewportView(jT2BookTable);

        jT2ClassTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane3.setViewportView(jT2ClassTable);

        jLabel7.setFont(new java.awt.Font("幼圆", 1, 14)); // NOI18N
        jLabel7.setText("教材信息");

        jLabel8.setFont(new java.awt.Font("幼圆", 1, 14)); // NOI18N
        jLabel8.setText("所带班级课程信息");

        jLabel9.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        jLabel9.setText("申请教材");

        jLabel10.setFont(new java.awt.Font("宋体", 2, 14)); // NOI18N
        jLabel10.setText("申请号");

        jLabel11.setFont(new java.awt.Font("宋体", 2, 14)); // NOI18N
        jLabel11.setText("申请教材号");

        jLabel12.setFont(new java.awt.Font("宋体", 2, 14)); // NOI18N
        jLabel12.setText("申请教师号");

        jLabel13.setFont(new java.awt.Font("宋体", 2, 14)); // NOI18N
        jLabel13.setText("申请数量");

        jLabel14.setFont(new java.awt.Font("宋体", 2, 14)); // NOI18N
        jLabel14.setText("申请日期");

        jT2Btn.setText("提交申请");
        jT2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT2BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(107, 107, 107)
                                                                                .addComponent(jLabel8)))
                                                                .addGap(63, 63, 63)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabel13)
                                                                                .addGap(225, 225, 225))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabel14)
                                                                                .addGap(156, 156, 156))))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(288, 288, 288))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                                                .addGap(268, 268, 268)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jLabel10)
                                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jLabel11)
                                                                                                .addComponent(jLabel12)))
                                                                                .addGap(55, 55, 55)))
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jT2ApplyNo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(jT2AppluNum)
                                                                                .addComponent(jT2ApplyTeacherNo)
                                                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jT2ApplyBookNo)
                                                                                .addComponent(jT2ApplyDate, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))))
                                                .addGap(122, 122, 122))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(138, 138, 138)
                                                .addComponent(jT2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(191, 191, 191))))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jT2ApplyNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel10))
                                                .addGap(37, 37, 37)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jT2ApplyBookNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel11))
                                                .addGap(45, 45, 45)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jT2ApplyTeacherNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel12))
                                                .addGap(46, 46, 46)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jT2AppluNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel13))
                                                .addGap(40, 40, 40)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jT2ApplyDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel14))
                                                .addGap(96, 96, 96)
                                                .addComponent(jT2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71))))
        );
        jTabbedPane1.addTab("教材申请", jPanel2);
        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jT3Table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane4.setViewportView(jT3Table);

        jLabel21.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel21.setText("我的申请记录");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(336, 336, 336))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("申请状态", jPanel3);

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));

        jLabel15.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel15.setText("修改个人信息");

        jLabel17.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        jLabel17.setText("姓名");

        jLabel18.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        jLabel18.setText("电话");

        jLabel19.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        jLabel19.setText("密码");

        jT4Btn.setText("提交修改");
        jT4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT4BtnActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        jLabel20.setText("科目");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(0, 0, 0)
                                                .addComponent(jT4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(120, 120, 120)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(jLabel20))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jT4Kemu)
                                                        .addComponent(jT4Name, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                                        .addComponent(jT4Tel)
                                                        .addComponent(jT4Pass))))
                                .addGap(198, 198, 198))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jT4Name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jT4Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jT4Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(jT4Kemu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addComponent(jT4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
        );

        jTabbedPane1.addTab("个人信息管理", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("班级信息录入");


        pack();
        //jT1模块
        jT1();
        jT2();
        jT3();
        jT4();
        jTabbedPane1.addChangeListener(e -> {
            if (jTabbedPane1.getSelectedIndex() == 0){
                String sqlShowJti = "select * from class";
                ShowTable.showTable(jT1Table,sqlShowJti,4,new String[]{"班级NO","班级编号","   专业","   人数"});
            }else if (jTabbedPane1.getSelectedIndex() == 1){
                String sql = "select Bno,Bname,Pname,Bprice from book,press where book.Pno = press.Pno";
                ShowTable.showTable(jT2BookTable,sql,4,new String[]{"教材编号","教材名称","教材出版社","教材价格"});
                String sq2 = "select Cname,Cnum,TCname from tc,class where tc.Cno = class.Cno and tc.Tno = '"+finalTeacherId+"'";
                ShowTable.showTable(jT2ClassTable,sq2,3,new String[]{"班级编号","班级人数","所带科目"});

            }else if (jTabbedPane1.getSelectedIndex() == 2){
                String sql = "select * from apply where Tno = "+"'"+finalTeacherId+"'";
                ShowTable.showTable(jT3Table,sql,6,new String[]{"申请编号","申请书编号","教师编号","申请数量","申请日期","被处理？"});
            }
        });

    }// </editor-fold>
    public void jT1(){
        String sqlShowJti = "select * from class";
        ShowTable.showTable(jT1Table,sqlShowJti,4,new String[]{"班级NO","班级编号","   专业","   人数"});
        jT1Table.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int  r = jT1Table.getSelectedRow();
                String cno = jT1Table.getValueAt(r,0).toString().trim();
                String cname = jT1Table.getValueAt(r,1).toString().trim();
                String cMajor = jT1Table.getValueAt(r,2).toString().trim();
                String num = jT1Table.getValueAt(r,3).toString().trim();
                jT1ClassNo.setText(cno);
                jT1ClassId.setText(cname);
                jT1ClassMajor.setText(cMajor);
                jT1ClassNum.setText(num);
            }
        });
        jT1Btn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String tcNo = "t"+jT1ClassNo.getText();
                String tNo =finalTeacherId;
                String cNo = jT1ClassNo.getText();
                String tName = jT1Kemu.getText();
                ModifyTable mModifyTable = new ModifyTable(mStatement);
                mModifyTable.setSql("insert into tc(TCno,Tno,Cno,TCname)values("
                        +"'"+tcNo+"'"+","
                        +"'"+tNo+"'"+","
                        +"'"+cNo+"'"+","
                        +"'"+tName+"')");
                mModifyTable.modifyRecord();
                System.out.println("添加成功");
                jT1ClassNo.setText("");
                jT1ClassId.setText("");
                jT1ClassMajor.setText("");
                jT1ClassNum.setText("");
                jT1Kemu.setText("");
                JOptionPane.showMessageDialog(TeacherActivity.this,"添加成功");
            }
        });


    }
    public void jT2(){
        String sql = "select Bno,Bname,Pname,Bprice from book,press where book.Pno = press.Pno";
        ShowTable.showTable(jT2BookTable,sql,4,new String[]{"教材编号","教材名称","教材出版社","教材价格"});
        String sq2 = "select Cname,Cnum,TCname from tc,class where tc.Cno = class.Cno and tc.Tno = '"+finalTeacherId+"'";
        ShowTable.showTable(jT2ClassTable,sq2,3,new String[]{"班级编号","班级人数","所带科目"});
        jT2ApplyTeacherNo.setText(finalTeacherId);
        jT2ApplyBookNo.setEditable(false);
        jT2Btn.addActionListener(e -> {
            String aNo = jT2ApplyNo.getText().trim();
            String bNo = jT2ApplyBookNo.getText().trim();
            System.out.println(bNo);
            String Tno = finalTeacherId;
            String aDate = jT2ApplyDate.getText().trim();
            int aNum1 = Integer.parseInt(jT2AppluNum.getText());
            ModifyTable mModifyTable = new ModifyTable(mStatement);
            mModifyTable.setSql("insert into apply(Ano,Bno,Tno,Anum,Adate)values("
                    +"'"+aNo+"'"+","
                    +"'"+bNo+"'"+","
                    +"'"+Tno+"'"+","
                    +" "+aNum1+" "+","
                    +"'"+aDate+"')");
            mModifyTable.modifyRecord();
            System.out.println("添加成功");
            jT2AppluNum.setText("");
            jT2ApplyDate.setText("");
            jT2ApplyNo.setText("");
            jT2ApplyBookNo.setText("");
            JOptionPane.showMessageDialog(TeacherActivity.this,"添加成功");
        });
    }
    public void jT3(){

        String sql = "select * from apply where Tno = "+"'"+finalTeacherId+"'";
        ShowTable.showTable(jT3Table,sql,6,new String[]{"申请编号","申请书编号","教师编号","申请数量","申请日期","被处理？"});

    }
    //
    public void jT4(){
        try {
            ResultSet mResultSet = mStatement.executeQuery("select * from teacher where Tno="+"'"+finalTeacherId+"'");
            if (mResultSet.next()){
                System.out.println("成功获取信息");
                jT4Kemu.setText(mResultSet.getString("Tdegree"));
                jT4Name.setText(mResultSet.getString("Tname"));
                jT4Pass.setText(mResultSet.getString("Tkey"));
                jT4Tel.setText(mResultSet.getString("Ttel"));
                jT4Btn.addActionListener(e -> {
                    mModifyTable.setSql("update teacher set Tname="+"'"+jT4Name.getText()+"' where Tno = "+"'"+finalTeacherId+"'");
                    mModifyTable.modifyRecord();
                    mModifyTable.setSql("update teacher set Tkey="+"'"+jT4Pass.getText()+"' where Tno = "+"'"+finalTeacherId+"'");
                    mModifyTable.modifyRecord();
                    mModifyTable.setSql("update teacher set Ttel="+"'"+jT4Tel.getText()+"' where Tno = "+"'"+finalTeacherId+"'");
                    mModifyTable.modifyRecord();
                    mModifyTable.setSql("update teacher set Tdegree="+"'"+jT4Kemu.getText()+"' where Tno = "+"'"+finalTeacherId+"'");
                    mModifyTable.modifyRecord();
                    JOptionPane.showMessageDialog(TeacherActivity.this,"修改成功");
                });
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
    private void jT1ClassNoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jT2BtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jT4BtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherActivity("test").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jT1Btn;
    private javax.swing.JTextField jT1ClassId;
    private javax.swing.JTextField jT1ClassMajor;
    private javax.swing.JTextField jT1ClassNo;
    private javax.swing.JTextField jT1ClassNum;
    private javax.swing.JTextField jT1Kemu;
    private javax.swing.JTable jT1Table;
    private javax.swing.JTextField jT2AppluNum;
    private javax.swing.JTextField jT2ApplyBookNo;
    private javax.swing.JTextField jT2ApplyDate;
    private javax.swing.JTextField jT2ApplyNo;
    private javax.swing.JTextField jT2ApplyTeacherNo;
    private javax.swing.JTable jT2BookTable;
    private javax.swing.JButton jT2Btn;
    private javax.swing.JTable jT2ClassTable;
    private javax.swing.JTable jT3Table;
    private javax.swing.JButton jT4Btn;
    private javax.swing.JTextField jT4Kemu;
    private javax.swing.JTextField jT4Name;
    private javax.swing.JTextField jT4Pass;
    private javax.swing.JTextField jT4Tel;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration
}
