package cn.edu.nuc.utils.Login;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import cn.edu.nuc.utils.DBSystemManage;
import cn.edu.nuc.utils.utils.ModifyTable;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Administrator
 */
public class TeacherRegistActivity extends JFrame {
    private Statement mStatement = DBSystemManage.getInstance().mStatement;

    /**
     * Creates new form TeacherRegistActivity
     */
    public TeacherRegistActivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jTextField1 = new JTextField();
        jTextField2 = new JTextField();
        jTextField4 = new JTextField();
        jTextField5 = new JTextField();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jComboBox1 = new JTextField();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("   教师注册界面");

        jLabel2.setText("教师编号：");

        jLabel3.setText("教师姓名：");

        jLabel4.setText("    科目：");

        jLabel5.setText("登录密码：");

        jLabel6.setText("联系方式");

        jButton1.setText("确定");
        jButton1.setActionCommand("确定");
        jButton1.addActionListener(e ->addActionListener(e));

        jButton2.setText("取消");
        jButton2.setActionCommand("取消");
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));


        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(197, 197, 197)
                                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 212, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGap(190, 190, 190)
                                                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                                        .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                                                .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(129, 129, 129)
                                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(139, 139, 139)
                                                                        .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)))
                                                        .addGap(33, 33, 33)
                                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jTextField1)
                                                                .addComponent(jTextField2)
                                                                .addComponent(jTextField4)
                                                                .addComponent(jTextField5)
                                                                .addComponent(jComboBox1, 0, 189, Short.MAX_VALUE)))))
                                .addGap(219, 219, 219))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(jLabel3))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel6))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>

    private void addActionListener(ActionEvent mE) {
        String Tno = jTextField1.getText();
        String Tname = jTextField2.getText();
        //kemu
        String Tsex = jComboBox1.getText();

        String Tpassword = jTextField4.getText();
        String Ttele = jTextField5 .getText();
        try {
            ResultSet mResultSet = mStatement.executeQuery("select * from teacher where Tno="+"'"+Tno+"'");
            //is result
            if (mResultSet.next()){
                JOptionPane.showMessageDialog(this,"用户已经存在");
            }else {
                if (!Tno.equals("")&&!Tname.equals("")&&!Tsex.equals("")&&!Tpassword.equals("")&&!Ttele.equals("")){
                    ModifyTable mModifyTable = new ModifyTable(mStatement);
                    mModifyTable.setSql("insert into teacher(Tno,Tname,Tkey,Tdegree,Ttel)values("
                            +"'"+Tno+"'"+","
                            +"'"+Tname+"'"+","
                            +"'"+Tpassword+"'"+","
                            +"'"+Tsex+"'"+","
                            +"'"+Ttele+"')");
                    mModifyTable.modifyRecord();
                    System.out.println("注册成功");
                    JOptionPane.showMessageDialog(this,"注册成功");

                    LoginActivity mLoginActivity = new LoginActivity();
                    mLoginActivity.setLocation(600,200);
                    mLoginActivity.setVisible(true);
                    this.setVisible(false);
                }else {
                    JOptionPane.showMessageDialog(this,"不能存在空值");
                }
            }
        } catch (SQLException mE1) {
            mE1.printStackTrace();
        }

    }

    private void jButton2ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
        LoginActivity mLoginActivity = new LoginActivity();
        mLoginActivity.setLocation(600,200);
        mLoginActivity.setVisible(true);
        this.setVisible(false);
    }

    // Variables declaration - do not modify
    private JButton jButton1;
    private JButton jButton2;
    private JTextField jComboBox1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JTextField jTextField1;
    private JTextField jTextField2;
    private JTextField jTextField4;
    private JTextField jTextField5;
    // End of variables declaration
}
